#!/usr/bin/perl -w

###################################
#
#    j-vs-t - Jabber -vs- Twitter
#
#     written by Martin Scharm
#       see http://binfalse.de
#
###################################

use warnings;
use strict;

use Net::Jabber::Bot;
use Net::Twitter;
use Date::Parse;
use HTML::Entities;
use Switch;

my $CONF_FILE = "j-vs-t.conf";
my $T_TOKEN = "t_token";
my $T_SECRET = "t_secret";
my $J_USER = "j_user";
my $J_PASS = "j_pass";
my $J_SERV = "j_serv";
my $J_AUTH_USER = "j_auth_user";
my $J_PORT = "j_port";
my $LAST_DATE = time()-6*60;
my $LAST_FRIENDS = 0;
my $LAST_MENTION = 0;
my $LAST_RETWEET = 0;
my $DEBUG = 1;

my $TWITTER = Net::Twitter->new(traits => ['API::REST', 'OAuth', 'WrapError'], consumer_key => "KVgWlkFUWezK5AvJeR6GQ", consumer_secret => "CjuLw8Bh9OHG4DO9lnZnQK6w3UvoqNR1DB7oBwEgb44",);

my ($t_token, $t_secret, $j_user, $j_pass, $j_serv, $j_auth_user, $j_port) = readConf ();
if ($t_token && $t_secret)
{
	$TWITTER->access_token($t_token);
	$TWITTER->access_token_secret($t_secret);
}

# our client isn't yet authorized...
unless ( $TWITTER->authorized )
{
	print "Authorize this client at ", $TWITTER->get_authorization_url, " and enter the PIN#\npin> ";
	my $pin = <STDIN>;
	chomp $pin;
	my($t_token, $t_secret, $user_id, $screen_name) = $TWITTER->request_access_token(verifier => $pin);
	writeConf ($CONF_FILE, $t_token, $t_secret, $j_user, $j_pass, $j_serv, $j_auth_user, $j_port);
}

my $bot = Net::Jabber::Bot->new ({server => $j_serv, port => $j_port, username => $j_user, password => $j_pass, alias => $j_user, message_function => \&messageCheck, background_function => \&updateCheck, loop_sleep_time => 40, process_timeout => 5, forums_and_responses => {}, ignore_server_messages => 1, ignore_self_messages => 1, out_messages_per_second => 20, max_message_size => 1000, max_messages_per_hour => 1000});

$bot->SendPersonalMessage($j_auth_user, "hey i'm back again!");
$bot->Start();

exit;


sub reauthTwitter
{
	$TWITTER = Net::Twitter->new(traits => ['API::REST', 'OAuth', 'WrapError'], consumer_key => "KVgWlkFUWezK5AvJeR6GQ", consumer_secret => "CjuLw8Bh9OHG4DO9lnZnQK6w3UvoqNR1DB7oBwEgb44",);
	$TWITTER->access_token($t_token);
	$TWITTER->access_token_secret($t_secret);
	sendJabber ("had to reauth twitter...");
}


sub readConf
{
	# read the config
	my $file = $CONF_FILE;
	my $t_token = undef;
	my $t_secret = undef;
	my $j_user = undef;
	my $j_pass = undef;
	my $j_serv = undef;
	my $j_auth_user = undef;
	my $j_port = undef;
	
	open(CF,'<'.$file) or return ("", "");
	
	while (my $line = <CF>)
	{
		next if($line =~ /^\s*#/);
		next if($line !~ /^\s*\S+\s*=.*$/);
		
		my ($key,$value) = split(/=/,$line,2);
		
		$key   =~ s/^\s+//g;
		$key   =~ s/\s+$//g;
		$value =~ s/^\s+//g;
		$value =~ s/\s+$//g;
		
		$t_token = $value if ($key eq $T_TOKEN);
		$t_secret = $value if ($key eq $T_SECRET);
		$j_user = $value if ($key eq $J_USER);
		$j_pass = $value if ($key eq $J_PASS);
		$j_serv = $value if ($key eq $J_SERV);
		$j_auth_user = $value if ($key eq $J_AUTH_USER);
		$j_port = $value if ($key eq $J_PORT);
	}
	close(CF);
	return ($t_token, $t_secret, $j_user, $j_pass, $j_serv, $j_auth_user, $j_port);
}
sub writeConf
{
	my $file = shift;
	my $t_token = shift;
	my $t_secret = shift;
	my $j_user = shift;
	my $j_pass = shift;
	my $j_serv = shift;
	my $j_auth_user = shift;
	my $j_port = shift;
	
	open(CF,'>'.$file) or die "failed to write to ".$file."\n";
	print CF "###########\n# TWITTER #\n###########\n# twitter token and secret to your account\n# (autogenerated - don't provide your username/password)\n";
	print CF "t_token = ".$t_token."\n";
	print CF "t_secret = ".$t_secret."\n\n";
	print CF "##########\n# JABBER #\n##########\n";
	print CF "# jabber account name of the bot\nj_user = ".$j_user."\n\n";
	print CF "# jabber password for the bot\nj_pass = ".$j_pass."\n\n";
	print CF "# jabber server\nj_serv = ".$j_serv."\n\n";
	print CF "# jabber user that is allowed to tweet\nj_auth_user = ".$j_auth_user."\n\n";
	print CF "# jabber port at the server (default 5222)\nj_port = ".$j_port."\n";
	close(CF);
}

sub updateCheck
{
	# check for new messages
	my $bot= shift;
	my $counter = shift;
	print "background " if ($DEBUG);
	my $tweets = $TWITTER->friends_timeline({count => 7});
	
	while (!defined($tweets))
	{
		reauthTwitter ();
		print "undef " if ($DEBUG);
		$tweets = $TWITTER->friends_timeline({count => 7});
		#$tweets = $TWITTER->friends_timeline({since_id => $LAST_FRIENDS});
		sleep 5;
	}
	print "got tweets " if ($DEBUG);
	my $new_date = $LAST_DATE;
	foreach my $hash_ref (@$tweets)
	{
		if ($LAST_DATE < str2time($hash_ref->{'created_at'}))
		{
			sendJabber ("<$hash_ref->{'user'}->{'screen_name'}>  " . decode_entities($hash_ref->{'text'}) . "  [at $hash_ref->{'created_at'}]");
			$new_date = str2time($hash_ref->{'created_at'}) if ($new_date < str2time($hash_ref->{'created_at'}));
			print "." if ($DEBUG);
		}
	}
	$tweets = $TWITTER->mentions({count => 7});
	#$tweets = $TWITTER->mentions({since_id => $LAST_MENTION});
	while (!$tweets)
	{
		reauthTwitter ();
		print "undef " if ($DEBUG);
		$tweets = $TWITTER->mentions({count => 7});
		#$tweets = $TWITTER->mentions({since_id => $LAST_MENTION});
		sleep 5;
	}
	print "got replies " if ($DEBUG);
	foreach my $hash_ref (@$tweets)
	{
		if ($LAST_DATE < str2time($hash_ref->{'created_at'}))
		{
			#sendJabber ("<$hash_ref->{'user'}->{'screen_name'}> replied:  " . decode_entities($hash_ref->{'text'}) . "  [at " . time2str ("%H:%M %d-%b-%Y", str2time ($hash_ref->{'created_at'}), "+0200") . "]");
			sendJabber ("<$hash_ref->{'user'}->{'screen_name'}> replied:  " . decode_entities($hash_ref->{'text'}) . "  [at $hash_ref->{'created_at'}]");
			$new_date = str2time($hash_ref->{'created_at'}) if ($new_date < str2time($hash_ref->{'created_at'}));
			print "." if ($DEBUG);
		}
	}
	$tweets = $TWITTER->retweeted_to_me({count => 7, since_id => $LAST_RETWEET});
	while (!$tweets)
	{
		reauthTwitter ();
		print "undef " if ($DEBUG);
		$tweets = $TWITTER->retweeted_to_me({count => 7, since_id => $LAST_RETWEET});
		sleep 5;
	}
	print "got retweets " if ($DEBUG);
	foreach my $hash_ref (@$tweets)
	{
			#sendJabber ("<$hash_ref->{'user'}->{'screen_name'}> replied:  " . decode_entities($hash_ref->{'text'}) . "  [at " . time2str ("%H:%M %d-%b-%Y", str2time ($hash_ref->{'created_at'}), "+0200") . "]");
			sendJabber ("<$hash_ref->{'user'}->{'screen_name'}> retweeted:  " . decode_entities($hash_ref->{'text'}) . "  [at $hash_ref->{'created_at'}]");
			$new_date = str2time($hash_ref->{'created_at'}) if ($new_date < str2time($hash_ref->{'created_at'}));
			print "." if ($DEBUG);
			$LAST_RETWEET = $hash_ref->{'id'} if ($hash_ref->{'id'} > $LAST_RETWEET);
	}
	print " done\n" if ($DEBUG);
	$LAST_DATE = $new_date;
}

sub messageCheck
{
	print "new msg arrived\n" if ($DEBUG);
	my %bot_message_hash = @_;
	
	$bot_message_hash{'sender'} = $bot_message_hash{'from_full'};
	$bot_message_hash{'sender'} =~ s{^(.+)\/.*$}{$1};
	
	# only the allowed user is able to speak to me
	return if ($bot_message_hash{'sender'} ne $j_auth_user);
	
	if ($bot_message_hash{body} =~ m/^!/)
	{
		# the user sends a command
		my($command, @options) = split(' ', $bot_message_hash{body});
		switch ($command)
		{
			case "!help"
			{
				sendJabber ("avaiable commands (commands begin with !):");
				sendJabber ("!help - print this help message");
				sendJabber ("!follow [USER] - follow the user USER");
				sendJabber ("!unfollow [USER] - stop following the user USER");
				sendJabber ("!profile [USER] - print the profile of USER");
				sendJabber ("!following - list the users you are following");
				sendJabber ("!followers - list the users that follow you");
				sendJabber ("all messages that doesn't start with ! are understood as status update");
			}
			case "!follow"
			{
				my $tofollow = $options[0];
				my $ret = $TWITTER->create_friend({ screen_name => $tofollow});
				if ($ret->{'screen_name'} eq $tofollow)
				{
					sendJabber ("you are now following " . $ret->{'screen_name'});
				}
				else
				{
					sendJabber ("failed to follow $tofollow: $ret");
				}
			}
			case "!unfollow"
			{
				my $tounfollow = $options[0];
				my $ret = $TWITTER->destroy_friend({ screen_name => $tounfollow});
				if ($ret->{'screen_name'} eq $tounfollow)
				{
					sendJabber ("you stopped following " . $ret->{'screen_name'});
				}
				else
				{
					sendJabber ("failed to unfollow $tounfollow: $ret");
				}
			}
			case "!profile"
			{
				my $user = $options[0];
				my $ret = $TWITTER->show_user({ screen_name => $user});
				if (ref $ret)
				{
					sendJabber ("name: $ret->{'name'}");
					sendJabber ("screen_name: $ret->{'screen_name'}");
					sendJabber ("id: $ret->{'id'}");
					sendJabber ("url: $ret->{'url'}");
					sendJabber ("language: $ret->{'lang'}");
					sendJabber ("created: $ret->{'created_at'}");
					sendJabber ("tweets: $ret->{'statuses_count'}");
					sendJabber ("following: $ret->{'friends_count'}");
					sendJabber ("followers: $ret->{'followers_count'}");
					sendJabber ("description: $ret->{'description'}");
					sendJabber ("favourites: $ret->{'favourites_count'}");
					sendJabber ("last status: $ret->{'status'}->{'text'} [$ret->{'status'}->{'created_at'}]");
				}
				else
				{
					sendJabber ("failed");
				}
			}
			case "!following"
			{
				my $ret = $TWITTER->friends();
				my @hash = @$ret;
				my $out = "you are following: ";
				foreach my $k (@hash )
				{
					$out .= "$k->{screen_name} ";
				}
				sendJabber ($out);
			}
			case "!followers"
			{
				my $ret = $TWITTER->followers();
				my @hash = @$ret;
				my $out = "your followers: ";
				foreach my $k (@hash )
				{
					$out .= "$k->{screen_name} ";
				}
				sendJabber ($out);
			}
			else
			{
				sendJabber ("what do you mean? try !help");
			}
		}
	}
	else
	{
		print "try to tweet\n" if ($DEBUG);
		tweet ($bot_message_hash{body});
	}
}

sub tweet
{
	# tweet the msg
	print "try to tweet\n" if ($DEBUG);
	my $status = shift;
	if (length $status > 140)
	{
		sendJabber ("you tried to send " . length ($status) . " characters, but only 140 are allowed...");
		sendJabber ("your message was: " . $status);
		return;
	}
	if (length $status < 1)
	{
		sendJabber ("you tried to send 0 characters, thats no status brother...");
		return;
	}
	
	print "try to tweet\n" if ($DEBUG);
	
	if ($TWITTER->update({ status => $status }))
	{
		sendJabber ("updated your status");
	}
	else
	{
		sendJabber ("failed to update your status");
		sendJabber ("your message was: " . $status);
		return;
	}
}

sub sendJabber
{
	# send a message to the authorized user
	$bot->SendPersonalMessage($j_auth_user, shift);
}
